# Business Analyst in Consulting

## Summary {-}

A business analyst consultant works with clients to help them understand and document business requirements. These requirements can be part of an IT-related project or a process improvement initiative. As a business analyst, or BA, you typically work for a consulting firm that charges clients an hourly rate for your time based on a negotiated contract. A BA travels to customer sites to meet directly with clients and view business operations firsthand. As a business analyst, you are expected to conduct surveys, perform statistical analyses and tests, make IT recommendations, suggest changes to certain processes, and create new systems.

## Education and Background {-}
Consulting is a wide industry with many different categories of consulting. The majority of  business analyst consultants have a bachelor's degree in business, engineering, or economics  with medium or high levels of data analysis or a coding background. As a result, some computer science students who are not looking for a programming job have also become interested in this industry in recent years. 



## Job Responsibilities {-}
Tasks are usually different for every project. However, most cases require you to evaluate your client’s business model or assess their potential risk in the future. Each case can range from a few weeks to multiple months of time to work while some may even take 6-10 months. However, you are expected to follow a certain framework given by either your client or your manager for your evaluation. You are expected to present clients with visualization of your evaluation along with your risk assessment and prediction for longevity in the future. Your final output will be professional yet easy to understand because your core value is the connection between hard-core data/technology and the normal people in the business world.

## Skill Sets {-}
Skills take on a more holistic approach as you are expected to be with customers and work through their problems with them and then report back to them.

 Soft Skills: 

 * Problem-solving
 * Make the Most of Presentations
 * Creative thinking
 * Be Flexible
 * Thinking conceptually and practically
 * Communicating clearly and empathetically
 * Collaboration with all job levels
 * Organization and time management
 * Curiosity
 * Credibility
 * “Consulting Fit” = Strong Academics with good experience and being apart of high achieving teams
 * Attention to detail
 
 Hard Skills:
 
 * Excel, Microsoft Outlook/Team, PowerPoint
 * ABAP, Tableau (If you are on technology track)

## Team Structure {-}
The team of a consultant is always changing depending on the nature of the current project. The team usually consists of a few business analysts.

The team you work with varies every project. Typically, there will be one Partner, one Senior Manager, one Junior Manager, several senior consultants, and each of these individuals will supervise a small number of Junior Consultants/Business Analysts. Usually partners and senior managers taking 99% of credit while doing 15% of work.
Team Dynamic
Typically, everyone works on their assigned jobs and meets their deadlines. People can become angry with one another if tasks are not completed on time or to specifications, and conflict can arise as a result.
The atmosphere is generally laid-back, although everyone is expected to put in a minimum of 40 hours per week. The lower your level, the more over time and menial labor you must perform.


## Work Life Balance {-}

Realistically, you’re on the clock from 9:00 AM to 9:00 PM and this may not include lunch, travel or dinner. Travel is very important because clients will be across the country and you are expected to meet them on time. 
You can expect 70-80 hour weeks. The very typical cycle is flying out on Monday and staying near the client until Thursday night or Friday Morning then flying. While flying, you are expected to work on the plane and in the airport. There is no overtime pay whatsoever because you are paid by commission on projects as well as salary. 

If you are not traveling, your manager will determine your work location. Some managers want you to be in the office every day, while others only require you to be there a few days each week or even allow you to work from home.


There is no day to day. Every day is different. You are working around the clock to finish your deliverables.

Performance is evaluated at the end of the year in December. Entry level analysts are evaluated on a bell curve where most clients are on the curve. If you are ranked greater than 50% of analysts, a larger bonus will be given. Analysts are graded on their yearly performance by their engagement manager and directors.


## Recruiting Information {-}
Recruiting for consulting is infamous for the difficult case preps. This requires learning the structure, developing a framework, asking qualifying questions and then answering technical and mental math problems. 
	Apply, 
	1st round Interview
	2nd Round Interview
	3rd Round Interview

## WWYD to prepare for this role (before applying) {-}
During the recruiting process, many may tell you it’s easy to switch tracks inside the firm. However, it wasn’t true for most companies. To be able to switch to another type of consulting within the same company, one needs to build connections with other case managers because they need to invite you to their team. You should also be aware that your working schedule is rarely 9-5 therefore make sure to prioritize your work life balance before you apply. 


## Resources at Ross {-}
At Ross, there are a few different resources for consulting preparation. Ross offers consulting clubs for students to join. There are consulting case competitions that professors host to help prepare students. 
Overall, there are peer coaching and career coaching interviews that you can sign up for to mock interviews. OYM coaches are always available to help prepare and give advice. 

## Industry Culture {-}
Consulting firms are extremely diverse. People will have plenty of possibilities to interact with people from various cultural backgrounds. In addition to compensation for most travel expenses, some companies also provide annual wellness funds. These funds may be used for anything that may help the physical and emotional wellbeing of employees.
However, despite its outward appearance of friendliness, there's always lots of politics and conflict going on behind scenes. Typically, company executives do the right thing and assist their staff to thrive, but their motivation is mostly financial.


## Trends in the Industry {-}
Consulting firms strive to keep up with market trends, and many firms have a tendency to establish relevant departments as quickly as feasible. Few companies have lately introduced a department dedicated to digital emerging technologies with an emphasis on block chain, NFT, and crypto currency in order to better serve their clients' needs in the digital world.

## Salary {-}
### Consulting Companies {-}
Please note these are estimated circa 2022
```{r, echo=FALSE}
tier0 = read.csv("csv/ConsultingSheet.csv")
knitr::kable(tier0, "pipe", col.names=c("Company", "Base Salary", "Maximum Performance Bonus"))
```

## Career Advancement and Exit Opportunities {-}
Similar to the majority of consulting positions, there are numerous prospects for career progression. In a few years, a large number of individuals would rise to Senior Consultant/Associate, Manager, Senior Manager, Team Leader, and ultimately Partner if they chose to advance vertically in the industry with managerial jobs. With the current industry trend favoring technology, big data, and computer programming consultants have new opportunities to enter these spaces especially those with a background in coding to take on roles such as data scientists or programming positions. In addition, many individuals who have worked for larger companies for a few years tend to switch to smaller companies in order to acquire greater control over the project in terms of duties, working hours, and salary.

Many consulting firms also sponsor MBA programs for their analysts after they have worked for a few years. Many consultants opt into these benefits to return to the company after schooling. 

