# Business Analyst in Finance
 
## Summary {-}

Financial analysts create financial plans for companies/clients, data oriented projections, and analytical reports for companies to use when making financial decisions. Financial analysts work for both public and private companies, along with individuals managing portfolios. They weigh micro and macroeconomic factors, and company values to make industry wide predictions. This profession is typically associated with working long hours receiving data, updating research, and adjusting models.

## Education & Background {-}

Bachelor’s degree in mathematics/finance/economics/business related field. Moving up to the senior level is possible with various certifications including Chartered Financial Analyst (CFA) certification, and earning an MBA. 

* CFA Certification - a series of exams to demonstrate competence - including advanced knowledge in accounting, economics, ethics, portfolio management, and security analysis.

## Job Responsibilities {-}

Job responsibilities include performing equity stress tests on the company’s asset portfolio and making financial projections. Some unspoken tasks of the job include downloading market data from bloomberg terminal, automating workflows.

## Work Life Balance {-}

The work life balance for BAs in tech is generally better than their counterparts in finance and consulting industries. They typically work for 8 to 10 hours per day. But since a BA is often asked to perform ad hoc analysis on internal and external data for project teams, the amount of daily responsibility varies greatly depending on the complexity of the project and the number of projects they have simultaneously. 

## Skill Sets {-}

High level analysts require skills/knowledge of statistics, finance, economics, and accounting. In order to be successful, financial analysts must be avid problem solvers, critical thinkers, and be able to quickly implement creative solutions. It is important to remain educated about market trends  and news cycles. Communication skills are a must.

## Recruiting Process {-}

A typical recruiting process for a financial analyst is similar to other sectors of business. Generally, a prospective analyst begins their career journey by researching companies that uphold similar values to their own. Factors including pay, benefits, remote flexibility, and geographical location are considered during the  decision making process. It is standard to reach out to a company analyst by email, and inquire more information about the company and overall industry, in pursuit of acquiring a referral from an internal employee. 

## Resources at Ross {-}

Ross Career Development Office offers recruiting support and career coaching for students interested in finance. Prospective analysts are advised to seek preemptive information before accepting a position. Typical inquiries include finding out whether  a promotion path is in place, what the workload is like at its  heaviest, major challenges, and potential team concerns.

## Industry Culture {-}

As the finance industry has transitioned to a more hybrid work environment, analysts have experienced some fundamental cultural changes. Although a more efficient, flexible timeline has developed, it’s become more common for work days to exceed into the evening hours resulting in an increase in employee burnout. Other factors impacting employee burnout rates include macroeconomic conditions, market ambiguity, potential risk of layoff, and issues with remote work. Some recent trends in the industry are RILA’s, which are annuities with safer rates for consumers. 

## WWYD to prepare for this role (before applying) {-}

## Salary {-}

Salary varies by region and cost of living in a particular location. Fully remote positions tend to pay more on average than in-person or hybrid ones.

* Junior Analyst: $60-110K

* Senior Analyst (3+ years):  $110-140K

* Median Pay: $86,660

## Career Advancement and Exit Opportunities {-}

Coding skills are important but being able to communicate with everyone is crucial to succeed as a financial analyst. One common career path involves earning a promotion to portfolio manager, then to Head of Financial Department, and possibly advancing to the C-suite as a Chief Financial Officer or Chief Executive Officer.
